server:
  port: 0
bot:
  name: '{cipher}1250f8aa831acbc58fd88a1ff9616029864bd54c353db5c6b57b8ebb29df7c43'
  token: '{cipher}e63dff8013719a2c30eb282d479655c2e43803313cce2696233f519d057a0e4cd498f731fdae0d8728614715f2466479f9c258f5b91bceb373c8a09ad816e939'
  receivers:
    - '{cipher}956ee2a6a596b83229167c4601c1739e57b7af3dd16ecaf123f78d485fbffd72'
    - '{cipher}dc4b512c83058dc247112d3ad297b46b7013fc958b7e21d00dae1a8311d82a78'
management:
  endpoints:
    web:
      exposure:
        include: '*'